spring:
  profiles:
    active: local

  jpa:
    show_sql: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.workm.kr:3306/dbworkm2023?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: workm2023
    password: workm!2023

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: jbkim404037@gmail.com
    password: awvrkaqpszcysnqr
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


server:
  servlet:
    jsp:
      init-parameters:
        development: true


custom:
  path:
    upload-images: '/dev/overworkgathering/images/'