spring:
  profiles:
    active: local

  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://overworkgatheringdb.cyficpszcokr.ap-northeast-2.rds.amazonaws.com:3306/OVER_WORK_GATHERING
    username: root
    password: abacusservice

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: jbkim404037@gmail.com
    password: awvrkaqpszcysnqr
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


server:
  servlet:
    jsp:
      init-parameters:
        development: true


custom:
  path:
    upload-images: '/dev/overworkgathering/images/'

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://overworkgatheringdb.cyficpszcokr.ap-northeast-2.rds.amazonaws.com:3306/OVER_WORK_GATHERING
    username: root
    password: abacusservice

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://overworkgatheringdb.cyficpszcokr.ap-northeast-2.rds.amazonaws.com:3306/OVER_WORK_GATHERING
    username: root
    password: abacusservice

---
spring:
  profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.239.124.246:14302/hong
    username: hong
    password: hong1234!